---
title: "FinalProject_WriteUp"
author: "Phoebe Jekielek and Sarah Risley"
date: "2022-11-30"
output: word_document
---

## Literature Notes

Here is where we will pull notes/quotes/frame our outline for the write up doc:


**Borthagaray et al., 2009** 
Best used in introduction, helpful for explaining richness and composition and the dynamics that influence these factors in marine/coastal habitats, why we're using UNTB.

"Here, we showed that for a rocky intertidal community the geographic distance, as proxy of landscape connectivity, is an important factor to explain the species richness and composition. We also found a linear decrease in species similarity with increasing geographic distance regardless of the functional group considered." (Borthagaray et al., 2009, p. 648)

"However, the strong relationship between geographic distance and species richness or composition supports the hypothesis that landscape connectivity is not as high as previously thought. Our results are therefore consistent with an alternative view suggesting that mean dispersal
distances of invertebrate larvae (25–150 km: Palumbi 2003) or rafting should not produce a high level of homogeneity." (Borthagaray et al., 2009, p. 648)

-Neutral- and niche-based mechanisms operate simultaneously

"In this sense, the pattern of variation in richness and composition of sessile species reported here is consistent with a lottery model and therefore with a neutral theory.Thus, when
dispersal is limited, in the neutral theory, nearby sessile communities should show similar biological composition due to the geographic proximity regardless of physical conditions or species differences in response to local conditions." (Borthagaray et al., 2009, p. 649)

"In summary, this paper shows that at the landscape scale, connectivity among sites can be important to understand the local structure of a marine community, in particular in the rocky intertidal zone...More connected patches tend to harbour more rich communities by increasing the
number of sessile species, what indirectly improve the condition to mobile ones, and more connected (between them) local communities tend to be more similar in species composition than more distant communities." (Borthagaray et al., 2009, p. 649) --> aka Tobler's law 

So...connectivity does matter, but ultimately the neutral model applies to these systems and is an appropriate method to understand species richness and composition in the intertidal. 

**Chisholm and Lichstein, 2009**
-dispersal into the local community governed by the immigration parameter m
-m lacks a clear biological interpretation
-They: Derive expressions for m based on the geometry of a plot defining the local community and the parameters of a dispersal kernal 
-looks at how SADs vary w/ varying spatial scale of observation 

"The immigration parameter m is the probability that a death in the local community is replaced by the offspring of an individual from outside the local community." (Chisholm and Lichstein, 2009, p. 1385) 

...put notes on hold because we moved more towards neutral theory in marine intertidal ecosystems.



**OUTLINE**

INTRO: (SR)
- NTB is commonly used in ecology to describe and understand biodiversity and evolution patterns (Rosindell et al., 2011; Wootton, 2005)
- Generally: NTB is for theoretical scenarios, rather than as a predictive model 
- Also, NTB is not commonly applied to marine systems
  -Cite the few papers that do deal with NTB (Alzante; Borthgaray et al., 2009; Dolan et al., 2007)
- Here we're looking to: 
  - Use NTB and competitive theory to evaluate how theoretical populations of shellfish will change over time under these scenarios in an estuary system 
  -What does increasing immigration of a rare species do to the biodiversity of the system? (i.e. species introduced from aquaculture or invasive)
  
Section 1:(PJ)
- What is NTB? (maybe Clark?)
- What is competitive theory? (need papers)

Section 2: (SR)
- System description: introduction of oysters and increases in green crab populations 
- Methods
  -NTB
  -Competitive
  
Section 3:
-Prelim results from models

Section 4:
- Discussion around special considerations for marine systems (Chust et al., 2016)
-Refutes NTB (Dornela et al., 2006)
  -What about different dispersal rates? (Srisvastava and Pavel, 2013)
  - How does the scale of observation influence model results? (Chisholm and Lichstein, 2009)
  -What about harvesting activity? How does that play into the NTB model? 
  -How does genetic manipulation from AQ influence biodiversity? 
  -Connolly et al., 2014
-What worked and didn't work 



















```{r cars}
summary(cars)
```

